# NumPy Random Sampling

**Track:** Data Science &nbsp;|&nbsp; **Task 13**

### Description
Generate random numbers and samples using NumPy and explore reproducibility using random seeds.

### Objective
Understand random data generation and its importance in data science experiments.

### Tools
- Python
- NumPy
- Jupyter Notebook


## 1. Setup

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.4.4


## 2. Random Integers and Floating-Point Numbers

NumPy's `random` module (via the modern `Generator` API, `np.random.default_rng`) can produce
random integers and random floats drawn from a uniform distribution.

In [2]:
# Create a random number generator
rng = np.random.default_rng()

# --- Random integers ---
single_int = rng.integers(1, 100)              # single random integer between 1 and 99
int_array = rng.integers(1, 100, size=10)       # array of 10 random integers
int_matrix = rng.integers(0, 10, size=(3, 4))   # 3x4 matrix of random integers 0-9

print("Single random integer (1-99):", single_int)
print("Array of 10 random integers (1-99):", int_array)
print("3x4 matrix of random integers (0-9):\n", int_matrix)

Single random integer (1-99): 10
Array of 10 random integers (1-99): [97 43 82 16  3  6 67  1 55 39]
3x4 matrix of random integers (0-9):
 [[2 7 2 3]
 [9 5 5 5]
 [1 2 3 8]]


In [3]:
# --- Random floating-point numbers ---
single_float = rng.random()               # single float in [0.0, 1.0)
float_array = rng.random(10)              # array of 10 floats in [0.0, 1.0)
uniform_range = rng.uniform(5, 15, size=5)  # 5 floats uniformly distributed between 5 and 15
normal_dist = rng.normal(loc=0, scale=1, size=5)  # 5 floats from a normal distribution

print("Single random float [0,1):", single_float)
print("Array of 10 random floats [0,1):", float_array)
print("5 floats uniform in [5, 15):", uniform_range)
print("5 floats from normal distribution (mean=0, std=1):", normal_dist)

Single random float [0,1): 0.610477700971669
Array of 10 random floats [0,1): [0.77894388 0.94788497 0.8739519  0.52232239 0.55164108 0.99966726
 0.98393294 0.46494291 0.34523825 0.38876507]
5 floats uniform in [5, 15): [ 8.8688705  11.91152834  6.09011219 11.66585116  9.85963096]
5 floats from normal distribution (mean=0, std=1): [-0.81721841 -0.96298448 -2.54917972  0.42497416  0.66088281]


## 3. Random Samples from an Array

`Generator.choice()` lets us draw random samples (with or without replacement) from an
existing array, and can also apply sampling weights/probabilities.

In [4]:
fruits = np.array(["apple", "banana", "cherry", "date", "elderberry", "fig", "grape"])

# Sample WITHOUT replacement (each element can be picked only once)
sample_no_replace = rng.choice(fruits, size=3, replace=False)

# Sample WITH replacement (an element can be picked multiple times)
sample_with_replace = rng.choice(fruits, size=5, replace=True)

# Weighted sampling: 'grape' is 5x more likely to be picked than the others
weights = np.array([1, 1, 1, 1, 1, 1, 5])
weights = weights / weights.sum()
weighted_sample = rng.choice(fruits, size=5, replace=True, p=weights)

print("Original array:", fruits)
print("Sample without replacement (3 items):", sample_no_replace)
print("Sample with replacement (5 items):", sample_with_replace)
print("Weighted sample (grape favored):", weighted_sample)

Original array: ['apple' 'banana' 'cherry' 'date' 'elderberry' 'fig' 'grape']
Sample without replacement (3 items): ['banana' 'date' 'grape']
Sample with replacement (5 items): ['date' 'elderberry' 'grape' 'apple' 'grape']
Weighted sample (grape favored): ['elderberry' 'banana' 'cherry' 'banana' 'fig']


In [5]:
# Shuffling an array in place is another common sampling-related operation
deck = np.arange(1, 11)
print("Before shuffle:", deck)
rng.shuffle(deck)
print("After shuffle: ", deck)

Before shuffle: [ 1  2  3  4  5  6  7  8  9 10]
After shuffle:  [ 2  3  9  5  7  8 10  6  1  4]


## 4. Reproducible Results Using a Seed

By default, every run of a random function gives different results. Setting a **seed**
makes the sequence of "random" numbers deterministic and repeatable — essential for
debugging and for sharing reproducible experiments with others.

In [6]:
# Without a seed: results differ every time the cell is run
gen_a = np.random.default_rng()
gen_b = np.random.default_rng()
print("Generator A:", gen_a.integers(0, 100, size=5))
print("Generator B:", gen_b.integers(0, 100, size=5))
print("Are they equal?", np.array_equal(gen_a.integers(0, 100, size=5), gen_b.integers(0, 100, size=5)))

Generator A: [92 57 29 92 13]
Generator B: [16 87 11 80 18]
Are they equal? False


In [7]:
# With a seed: results are identical every single run
seeded_gen_1 = np.random.default_rng(seed=42)
seeded_gen_2 = np.random.default_rng(seed=42)

result_1 = seeded_gen_1.integers(0, 100, size=5)
result_2 = seeded_gen_2.integers(0, 100, size=5)

print("Seeded Generator 1:", result_1)
print("Seeded Generator 2:", result_2)
print("Are they equal?", np.array_equal(result_1, result_2))

Seeded Generator 1: [ 8 77 65 43 43]
Seeded Generator 2: [ 8 77 65 43 43]
Are they equal? True


## 5. Generating a Small Simulated Dataset

Putting it all together: a small reproducible synthetic dataset of "student marks",
similar in spirit to the suggested **Student Marks Dataset**.

In [8]:
rng_seeded = np.random.default_rng(seed=7)

n_students = 10
student_ids = np.arange(1, n_students + 1)
# Marks simulated from a normal distribution, clipped to a valid 0-100 range
marks = rng_seeded.normal(loc=70, scale=12, size=n_students)
marks = np.clip(marks, 0, 100).round(1)

print("Student ID :", student_ids)
print("Marks      :", marks)
print("Average mark:", marks.mean().round(2))

Student ID : [ 1  2  3  4  5  6  7  8  9 10]
Marks      : [70.  73.6 66.7 59.3 64.5 58.1 70.7 86.1 64.1 62.6]
Average mark: 67.57


In [9]:
# Verify reproducibility of the simulated dataset: re-running with the same seed
# produces the exact same 'random' marks.
rng_check = np.random.default_rng(seed=7)
marks_check = np.clip(rng_check.normal(loc=70, scale=12, size=n_students), 0, 100).round(1)

print("Original marks: ", marks)
print("Recomputed marks:", marks_check)
print("Identical?", np.array_equal(marks, marks_check))

Original marks:  [70.  73.6 66.7 59.3 64.5 58.1 70.7 86.1 64.1 62.6]
Recomputed marks: [70.  73.6 66.7 59.3 64.5 58.1 70.7 86.1 64.1 62.6]
Identical? True


## 6. Interview Questions

**Q1. Why are random numbers useful in data science?**

Random numbers are used to simulate data when real data isn't available, to split
datasets into training/validation/test sets, to initialize model parameters (e.g. neural
network weights), to perform bootstrapping and cross-validation, to run Monte Carlo
simulations, and to shuffle data so that models don't learn spurious patterns tied to
the original data order.

**Q2. What is a random seed?**

A random seed is a starting value given to a pseudo-random number generator. Computers
can't generate *truly* random numbers — they use deterministic algorithms that produce
a long sequence of numbers that only *look* random. The seed determines exactly where in
that sequence the generator starts, so the same seed always produces the same sequence
of "random" numbers.

**Q3. Why is reproducibility important?**

Reproducibility means that an experiment, when re-run under the same conditions,
produces the same results. This matters because it lets other people (or your future
self) verify results, debug code reliably, fairly compare different models or
approaches on identical data splits/initializations, and trust that reported results
aren't just a lucky roll of the dice.
